# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline to YC
env:
  YANDEX_OBJECT_STORAGE_NAME : "flask-application-packages"
  

on:
  push:
    branches: [ "main" ]

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@1
      
    
  
